import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MicrophoneContextProvider } from "./context/MicrophoneContextProvider";
import { DeepgramContextProvider } from "./context/DeepgramContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {
          <MicrophoneContextProvider>
            <DeepgramContextProvider>{children}</DeepgramContextProvider>
          </MicrophoneContextProvider>
        }
      </body>
    </html>
  );
}
